-- MySQL Script generated by MySQL Workbench
-- 06/07/15 23:13:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sandeepni
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sandeepni
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sandeepni` DEFAULT CHARACTER SET utf8 ;
USE `sandeepni` ;

-- -----------------------------------------------------
-- Table `sandeepni`.`acos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sandeepni`.`acos` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `parent_id` INT(10) NULL DEFAULT NULL,
  `model` VARCHAR(255) NULL DEFAULT NULL,
  `foreign_key` INT(10) NULL DEFAULT NULL,
  `alias` VARCHAR(255) NULL DEFAULT NULL,
  `lft` INT(10) NULL DEFAULT NULL,
  `rght` INT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_acos_lft_rght` (`lft` ASC, `rght` ASC),
  INDEX `idx_acos_alias` (`alias` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 53
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sandeepni`.`aros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sandeepni`.`aros` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `parent_id` INT(10) NULL DEFAULT NULL,
  `model` VARCHAR(255) NULL DEFAULT NULL,
  `foreign_key` INT(10) NULL DEFAULT NULL,
  `alias` VARCHAR(255) NULL DEFAULT NULL,
  `lft` INT(10) NULL DEFAULT NULL,
  `rght` INT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_aros_lft_rght` (`lft` ASC, `rght` ASC),
  INDEX `idx_aros_alias` (`alias` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sandeepni`.`aros_acos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sandeepni`.`aros_acos` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `aro_id` INT(10) NOT NULL,
  `aco_id` INT(10) NOT NULL,
  `_create` VARCHAR(2) NOT NULL DEFAULT '0',
  `_read` VARCHAR(2) NOT NULL DEFAULT '0',
  `_update` VARCHAR(2) NOT NULL DEFAULT '0',
  `_delete` VARCHAR(2) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ARO_ACO_KEY` (`aro_id` ASC, `aco_id` ASC),
  INDEX `idx_aco_id` (`aco_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sandeepni`.`cake_sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sandeepni`.`cake_sessions` (
  `id` VARCHAR(255) NOT NULL,
  `data` TEXT NULL DEFAULT NULL,
  `expires` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sandeepni`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sandeepni`.`countries` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `alias` VARCHAR(5) NOT NULL,
  `status` TINYINT(2) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 235
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sandeepni`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sandeepni`.`groups` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL COMMENT 'name of group',
  `status` CHAR(1) NOT NULL DEFAULT 'f' COMMENT 't=true, f=false',
  `created` DATETIME NOT NULL COMMENT 'when group created',
  `modified` DATETIME NOT NULL COMMENT 'when group modified',
  `is_delete` TINYINT(2) NOT NULL DEFAULT '0' COMMENT '1=deleted, 0=active',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 508
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sandeepni`.`logins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sandeepni`.`logins` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `group_id` INT(11) NOT NULL COMMENT 'id of group table',
  `username` VARCHAR(64) NOT NULL,
  `password` TEXT NOT NULL,
  `status` CHAR(1) NOT NULL DEFAULT 'f' COMMENT 't=true, f=false',
  `is_delete` TINYINT(2) NOT NULL DEFAULT '0' COMMENT '1=deleted, 0=active',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 112
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sandeepni`.`mails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sandeepni`.`mails` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `login_id` INT(11) NOT NULL COMMENT 'id of login table',
  `to` VARCHAR(256) NOT NULL COMMENT 'sender email',
  `subject` VARCHAR(256) NOT NULL COMMENT 'subject of email',
  `msg` TEXT NOT NULL COMMENT 'message of email',
  `type` TINYINT(5) NOT NULL COMMENT '1=inbox, 2=draft, 3=Trash, 4=sent',
  `status` CHAR(1) NOT NULL DEFAULT 'f' COMMENT 't=true, f=false',
  `created` DATETIME NOT NULL COMMENT 'when email created',
  `modified` DATETIME NOT NULL COMMENT 'when email modified',
  `is_delete` TINYINT(2) NOT NULL DEFAULT '0' COMMENT '1=deleted, 0=active',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sandeepni`.`modification_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sandeepni`.`modification_logs` (
  `id` INT(11) NOT NULL,
  `login_id` INT(11) NOT NULL COMMENT 'id of login table',
  `text` TEXT NULL DEFAULT NULL,
  `status` CHAR(1) NOT NULL DEFAULT 'f' COMMENT 't=true, f=false',
  `created` DATETIME NOT NULL COMMENT 'when modification created',
  `modified` DATETIME NOT NULL COMMENT 'when modification modified',
  `is_delete` TINYINT(2) NOT NULL DEFAULT '0' COMMENT '1=deleted, 0=active',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sandeepni`.`student_folder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sandeepni`.`student_folder` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'id of student table',
  `student_id` INT(11) NOT NULL COMMENT 'id of student table',
  `name` VARCHAR(256) NOT NULL COMMENT 'original student file name',
  `description` TEXT NOT NULL COMMENT 'information about student file',
  `enc_name` VARCHAR(256) NOT NULL COMMENT 'encrypted student file name',
  `width` VARCHAR(20) NOT NULL COMMENT 'width of student file',
  `height` VARCHAR(20) NOT NULL COMMENT 'height of student file',
  `type` VARCHAR(45) NOT NULL COMMENT 'student file type',
  `status` CHAR(1) NOT NULL DEFAULT 'f' COMMENT 't=true, f=false',
  `created` DATETIME NULL DEFAULT NULL COMMENT 'when student file created',
  `modified` DATETIME NULL DEFAULT NULL COMMENT 'when student file modified',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sandeepni`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sandeepni`.`students` (
  `id` INT(11) NOT NULL,
  `login_id` INT(11) NOT NULL COMMENT 'id of login table',
  `registration_no` VARCHAR(256) NOT NULL COMMENT 'registration number of student',
  `first_name` VARCHAR(45) NOT NULL COMMENT 'first name of student',
  `middle_name` VARCHAR(45) NULL DEFAULT NULL COMMENT 'middile name of student',
  `last_name` VARCHAR(45) NOT NULL COMMENT 'last name of student',
  `father_name` VARCHAR(45) NOT NULL COMMENT 'father name of student',
  `father_occupation` VARCHAR(45) NULL DEFAULT NULL COMMENT 'what is father work of student',
  `father_qualification` VARCHAR(45) NULL DEFAULT NULL COMMENT 'what is father qualification of student',
  `mother_name` VARCHAR(45) NULL DEFAULT NULL COMMENT 'mother name of student',
  `mother_occupation` VARCHAR(45) NULL DEFAULT NULL COMMENT 'what is mother work of student',
  `mother_qualification` VARCHAR(45) NULL DEFAULT NULL COMMENT 'what is mother qualifcation of student',
  `guardian_name` VARCHAR(45) NULL DEFAULT NULL COMMENT 'who is taking care(guardian) name of student',
  `guardian_occupation` VARCHAR(45) NULL DEFAULT NULL COMMENT 'what is guardian work of student',
  `guardian_qualification` VARCHAR(45) NULL DEFAULT NULL COMMENT 'what is guardian qualification of student',
  `gender` ENUM('M','F') NOT NULL COMMENT 'M=Male, F=Female',
  `dob` DATE NOT NULL COMMENT 'date of birth of student',
  `class` VARCHAR(45) NOT NULL COMMENT 'what is class of student',
  `session` VARCHAR(45) NOT NULL COMMENT 'session year of student',
  `stream` VARCHAR(45) NOT NULL COMMENT 'subjects of student',
  `height` VARCHAR(45) NULL DEFAULT NULL COMMENT 'height of student',
  `weight` VARCHAR(45) NULL DEFAULT NULL COMMENT 'weight of student',
  `hobbies` VARCHAR(45) NULL DEFAULT NULL COMMENT 'hobbies of student',
  `resident_type` TINYINT(2) NOT NULL COMMENT '1=Border,2=Day Border',
  `joining_date` DATE NULL DEFAULT NULL COMMENT 'joining date of student',
  `left_date` DATE NULL DEFAULT NULL,
  `student_status` TINYINT(2) NOT NULL COMMENT '1=Left, 2=Regular',
  `p_address` TEXT NULL DEFAULT NULL COMMENT 'permanent address of student',
  `p_country` VARCHAR(45) NULL DEFAULT NULL COMMENT 'permanent country of student',
  `p_state` VARCHAR(45) NULL DEFAULT NULL COMMENT 'permanent state of student',
  `p_district` VARCHAR(45) NULL DEFAULT NULL COMMENT 'permanent district of student',
  `p_city` VARCHAR(45) NULL DEFAULT NULL COMMENT 'permanent city of student',
  `p_pincode` INT(11) NULL DEFAULT NULL COMMENT 'permanent  pincode of student',
  `c_address` TEXT NULL DEFAULT NULL COMMENT 'temporary addrss of student ',
  `c_country` VARCHAR(45) NULL DEFAULT NULL COMMENT 'temporary country of student',
  `c_state` VARCHAR(45) NULL DEFAULT NULL COMMENT 'temporary state of student',
  `c_district` VARCHAR(45) NULL DEFAULT NULL COMMENT 'temporary district of student',
  `c_city` VARCHAR(45) NULL DEFAULT NULL COMMENT 'temporary city of student',
  `c_pincode` INT(11) NULL DEFAULT NULL COMMENT 'temporary pincode of student',
  `bus_no` VARCHAR(45) NULL DEFAULT NULL COMMENT 'In which bus student travel',
  `telephone` VARCHAR(45) NULL DEFAULT NULL COMMENT 'landline number of student',
  `mobile` INT(10) NULL DEFAULT NULL COMMENT 'mobile number of student',
  `email` VARCHAR(225) NULL DEFAULT NULL COMMENT 'email id of student',
  `status` CHAR(1) NOT NULL DEFAULT 'f' COMMENT 't=true, f=false',
  `created` DATETIME NOT NULL COMMENT 'when student created',
  `modified` DATETIME NOT NULL COMMENT 'when student modified',
  `is_delete` TINYINT(2) NOT NULL DEFAULT '0' COMMENT '1=deleted, 0=active',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sandeepni`.`user_folder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sandeepni`.`user_folder` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'id of login table',
  `user_id` INT(11) NOT NULL COMMENT 'id of users table',
  `name` VARCHAR(256) NOT NULL COMMENT 'original user file name',
  `description` VARCHAR(45) NOT NULL COMMENT 'information about file',
  `x` VARCHAR(128) NOT NULL,
  `y` VARCHAR(128) NOT NULL,
  `width` VARCHAR(20) NOT NULL COMMENT 'width of user file',
  `height` VARCHAR(20) NOT NULL COMMENT 'height of user file',
  `type` VARCHAR(45) NOT NULL COMMENT 'user file type',
  `status` CHAR(1) NOT NULL DEFAULT 'f' COMMENT 't=true, f=false',
  `created` DATETIME NULL DEFAULT NULL COMMENT 'when user file created',
  `modified` DATETIME NULL DEFAULT NULL COMMENT 'when user file modified',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sandeepni`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sandeepni`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `login_id` INT(11) NOT NULL COMMENT 'id of login table',
  `email` VARCHAR(256) NOT NULL COMMENT 'email of user',
  `first_name` VARCHAR(64) NOT NULL COMMENT 'first name of user',
  `last_name` VARCHAR(64) NOT NULL COMMENT 'last name of user',
  `dob` DATE NULL DEFAULT NULL COMMENT 'date of birth of user',
  `mobile` TEXT NOT NULL COMMENT 'mobile number of user',
  `interest` VARCHAR(256) NOT NULL COMMENT 'what is interest of user (seperated with comma)',
  `occupation` VARCHAR(256) NOT NULL COMMENT 'what is work of user ',
  `about` TEXT NOT NULL COMMENT 'Information about user',
  `country` VARCHAR(45) NULL DEFAULT 'India' COMMENT 'country of user',
  `state` VARCHAR(64) NOT NULL COMMENT 'state of user',
  `city` VARCHAR(64) NOT NULL COMMENT 'city of user',
  `address` TEXT NOT NULL COMMENT 'address of user',
  `token` VARCHAR(255) NOT NULL COMMENT 'token is used to check user to reset password',
  `attempt` TINYINT(5) NULL DEFAULT NULL COMMENT 'how many time user try to login',
  `attempt_date` DATE NULL DEFAULT NULL COMMENT 'last user login date',
  `server_name` VARCHAR(125) NULL DEFAULT NULL COMMENT 'server name',
  `server_add` TEXT NULL DEFAULT NULL COMMENT 'IP address',
  `browser` TEXT NULL DEFAULT NULL COMMENT 'browser name',
  `created` DATETIME NOT NULL COMMENT 'when user created.',
  `modified` DATETIME NOT NULL COMMENT 'when user modified.',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 62
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
